# Generated by Django 4.0.3 on 2023-06-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='End_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('registration_date', models.DateField()),
                ('registration_time', models.TimeField()),
                ('_password', models.CharField(max_length=256)),
            ],
        ),
    ]
